language: ruby

script:
  rspec --backtrace

before_install:
  - gem install bundler

rvm:
  - 2.6.6
  - 2.7.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  irc: "irc.freenode.org#pry"

branches:
  only:
    - master
